/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.io.nevill.boardwalk.Console');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('proto.io.nevill.boardwalk.ConsoleContents');
goog.require('proto.io.nevill.boardwalk.Selector');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.nevill.boardwalk.Console = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.io.nevill.boardwalk.Console.repeatedFields_, null);
};
goog.inherits(proto.io.nevill.boardwalk.Console, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.io.nevill.boardwalk.Console.displayName = 'proto.io.nevill.boardwalk.Console';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.io.nevill.boardwalk.Console.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.nevill.boardwalk.Console.prototype.toObject = function(opt_includeInstance) {
  return proto.io.nevill.boardwalk.Console.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.nevill.boardwalk.Console} msg The msg instance to transform.
 * @return {!Object}
 */
proto.io.nevill.boardwalk.Console.toObject = function(includeInstance, msg) {
  var f, obj = {
    title: jspb.Message.getFieldWithDefault(msg, 1, ""),
    selectorsList: jspb.Message.toObjectList(msg.getSelectorsList(),
    proto.io.nevill.boardwalk.Selector.toObject, includeInstance),
    contentsList: jspb.Message.toObjectList(msg.getContentsList(),
    proto.io.nevill.boardwalk.ConsoleContents.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.nevill.boardwalk.Console}
 */
proto.io.nevill.boardwalk.Console.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.nevill.boardwalk.Console;
  return proto.io.nevill.boardwalk.Console.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.nevill.boardwalk.Console} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.nevill.boardwalk.Console}
 */
proto.io.nevill.boardwalk.Console.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 2:
      var value = new proto.io.nevill.boardwalk.Selector;
      reader.readMessage(value,proto.io.nevill.boardwalk.Selector.deserializeBinaryFromReader);
      msg.addSelectors(value);
      break;
    case 3:
      var value = new proto.io.nevill.boardwalk.ConsoleContents;
      reader.readMessage(value,proto.io.nevill.boardwalk.ConsoleContents.deserializeBinaryFromReader);
      msg.addContents(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.nevill.boardwalk.Console.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.nevill.boardwalk.Console.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.nevill.boardwalk.Console} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.io.nevill.boardwalk.Console.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSelectorsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.io.nevill.boardwalk.Selector.serializeBinaryToWriter
    );
  }
  f = message.getContentsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.io.nevill.boardwalk.ConsoleContents.serializeBinaryToWriter
    );
  }
};


/**
 * optional string title = 1;
 * @return {string}
 */
proto.io.nevill.boardwalk.Console.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.io.nevill.boardwalk.Console.prototype.setTitle = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * repeated Selector selectors = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.io.nevill.boardwalk.Selector>}
 */
proto.io.nevill.boardwalk.Console.prototype.getSelectorsList = function() {
  return /** @type{!Array.<!proto.io.nevill.boardwalk.Selector>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.io.nevill.boardwalk.Selector, 2));
};


/** @param {!Array.<!proto.io.nevill.boardwalk.Selector>} value */
proto.io.nevill.boardwalk.Console.prototype.setSelectorsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.io.nevill.boardwalk.Selector=} opt_value
 * @param {number=} opt_index
 * @return {!proto.io.nevill.boardwalk.Selector}
 */
proto.io.nevill.boardwalk.Console.prototype.addSelectors = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.io.nevill.boardwalk.Selector, opt_index);
};


proto.io.nevill.boardwalk.Console.prototype.clearSelectorsList = function() {
  this.setSelectorsList([]);
};


/**
 * repeated ConsoleContents contents = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.io.nevill.boardwalk.ConsoleContents>}
 */
proto.io.nevill.boardwalk.Console.prototype.getContentsList = function() {
  return /** @type{!Array.<!proto.io.nevill.boardwalk.ConsoleContents>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.io.nevill.boardwalk.ConsoleContents, 3));
};


/** @param {!Array.<!proto.io.nevill.boardwalk.ConsoleContents>} value */
proto.io.nevill.boardwalk.Console.prototype.setContentsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.io.nevill.boardwalk.ConsoleContents=} opt_value
 * @param {number=} opt_index
 * @return {!proto.io.nevill.boardwalk.ConsoleContents}
 */
proto.io.nevill.boardwalk.Console.prototype.addContents = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.io.nevill.boardwalk.ConsoleContents, opt_index);
};


proto.io.nevill.boardwalk.Console.prototype.clearContentsList = function() {
  this.setContentsList([]);
};


