/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.io.nevill.boardwalk.Graph');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('proto.io.nevill.boardwalk.GraphQuery');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.nevill.boardwalk.Graph = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.io.nevill.boardwalk.Graph.repeatedFields_, null);
};
goog.inherits(proto.io.nevill.boardwalk.Graph, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.io.nevill.boardwalk.Graph.displayName = 'proto.io.nevill.boardwalk.Graph';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.io.nevill.boardwalk.Graph.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.io.nevill.boardwalk.Graph.prototype.toObject = function(opt_includeInstance) {
  return proto.io.nevill.boardwalk.Graph.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.io.nevill.boardwalk.Graph} msg The msg instance to transform.
 * @return {!Object}
 */
proto.io.nevill.boardwalk.Graph.toObject = function(includeInstance, msg) {
  var f, obj = {
    queriesList: jspb.Message.toObjectList(msg.getQueriesList(),
    proto.io.nevill.boardwalk.GraphQuery.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.nevill.boardwalk.Graph}
 */
proto.io.nevill.boardwalk.Graph.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.io.nevill.boardwalk.Graph;
  return proto.io.nevill.boardwalk.Graph.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.nevill.boardwalk.Graph} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.nevill.boardwalk.Graph}
 */
proto.io.nevill.boardwalk.Graph.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.io.nevill.boardwalk.GraphQuery;
      reader.readMessage(value,proto.io.nevill.boardwalk.GraphQuery.deserializeBinaryFromReader);
      msg.addQueries(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.nevill.boardwalk.Graph.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.io.nevill.boardwalk.Graph.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.nevill.boardwalk.Graph} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.io.nevill.boardwalk.Graph.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQueriesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.io.nevill.boardwalk.GraphQuery.serializeBinaryToWriter
    );
  }
};


/**
 * repeated GraphQuery queries = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.io.nevill.boardwalk.GraphQuery>}
 */
proto.io.nevill.boardwalk.Graph.prototype.getQueriesList = function() {
  return /** @type{!Array.<!proto.io.nevill.boardwalk.GraphQuery>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.io.nevill.boardwalk.GraphQuery, 1));
};


/** @param {!Array.<!proto.io.nevill.boardwalk.GraphQuery>} value */
proto.io.nevill.boardwalk.Graph.prototype.setQueriesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.io.nevill.boardwalk.GraphQuery=} opt_value
 * @param {number=} opt_index
 * @return {!proto.io.nevill.boardwalk.GraphQuery}
 */
proto.io.nevill.boardwalk.Graph.prototype.addQueries = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.io.nevill.boardwalk.GraphQuery, opt_index);
};


proto.io.nevill.boardwalk.Graph.prototype.clearQueriesList = function() {
  this.setQueriesList([]);
};


